spring.application.name=notes-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notesdb}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Sandesh@2004}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=THIS_IS_MY_SECRET_KEY_123456789_FOR_HS256_TOKEN_SIGNING
jwt.expiration=86400000

logging.level.root=INFO
logging.level.com.sandesh.notesapi=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

management.endpoints.web.exposure.include=*

server.forward-headers-strategy=framework